import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import Footer from "@/components/Footer";
import { FaChartBar, FaComments, FaCompass, FaHome, FaSlidersH } from "react-icons/fa";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { href: '/', icon: <FaHome />, text: 'Home 🏠' },
  { href: '/dashboard', icon: <FaSlidersH />, text: 'Dashboard 📊' },
  { href: '/discover', icon: <FaCompass />, text: 'Discover 🔍' },
  { href: '/chats', icon: <FaComments />, text: 'Chats 💬' },
  { href: '/reports', icon: <FaChartBar />, text: 'Reports 📈' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json"/>
      </head>
      <body className={inter.className}>
      <Navbar id={"Ramesh"} links={links} footer={<Footer/>}></Navbar>
        {children}
      </body>
    </html>
  );
}
